### ISSUE TITLE
How to Run/Compile ProgQuery using Java8

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [OscarRodriguezPrieto/ProgQuery#12]
Hi, 
I'm having issues with running ProgQuery. I keep on getting errors. I followed the exact process that you mentioned. Downloaded the contents of binaries folder in my root, and ran the quury. Based on what arguments I pass I get different error.

`javac -cp ProgQuery.jar;libs; -Xplugin:"ProgQueryPlugin neo4j L"  Blabla.java

A plugin threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoClassDefFoundError: org/neo4j/graphdb/Label
        at ProgQueryPlugin.init(ProgQueryPlugin.java:29)
        at com.sun.tools.javac.main.Main.compile(Main.java:470)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
Caused by: java.lang.ClassNotFoundException: org.neo4j.graphdb.Label
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more`

**Since java was not getting subfolders in classpath, I add libs/neo4j4 folder to the classpath aswell, no I get a different error.** 

`javac -cp ProgQuery.jar;libs/*;libs/neo4j4/*;classes; -Xplugin:"ProgQueryPlugin neo4j L"  Blabla.java

A plugin threw an uncaught exception.
Consult the following stack trace for details.
java.lang.UnsupportedClassVersionError: org/neo4j/graphdb/Label has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at ProgQueryPlugin.init(ProgQueryPlugin.java:36)
        at com.sun.tools.javac.main.Main.compile(Main.java:470)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)`

**I'm getting this error because of java version incompatability. I'm using Java 8, but looks like to generated the Jar files using a different version of Java.** I got the same error even in server mode 

`javac -classpath "ProgQuery.jar;libs/*;libs/neo4j4/*"  -Xplugin:"ProgQueryPlugin L"  Blabla.java javac -Xplugin:"ProgQueryPlugin neo4j S neo4j;neo4j;bolt://localhost:7687"  Blabla.java

A plugin threw an uncaught exception.
Consult the following stack trace for details.
java.lang.UnsupportedClassVersionError: org/neo4j/graphdb/Label has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at ProgQueryPlugin.init(ProgQueryPlugin.java:29)
        at com.sun.tools.javac.main.Main.compile(Main.java:470)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)`

Could you please share how to compile your source code(ex: POM file ) for Java 8. Or detailed steps that I need to follow to get rid of this errors .

**Comment by OscarRodriguezPrieto** [comment]
Hi SumanthReddyKaliki

The first error is caused because you did not add one folder with dependencies (the one containing org/neo4j/graphdb/Label and more deps) to the classpath, you wrote:
javac -cp ProgQuery.jar;libs; -Xplugin:"ProgQueryPlugin neo4j L" Blabla.java
But it should have been like this:
javac -cp ProgQuery.jar;libs\*;libs\neo4j\*; -Xplugin:"ProgQueryPlugin projectName L" Blabla.java

The following errors were caused because there is no stable version of ProgQuery running with Neo4j 4 yet. You should download the binaries of the last release, specify the correct routes in the classpath (for all the dependencies folders), and follow the README.md for the plugin arguments. If you have any other problem or question, please add another issue and I will answer as soon as possible. There is no problem running the current release of ProgQuery with Java 13, as I have just run it, and it works.

**Comment by SumanthReddyKaliki** [comment]
Hi, thanks for the reply. Like I said I fixed the first issue by specifying correct dependencies. 

**By My issues is different. Because our source code only suports java 8, I can only use JDK 8** 

**But the ProgQuery is complied using higher version of Java (Java 13)**. Because  of that I'm getting an error 

`java.lang.UnsupportedClassVersionError: ProgQueryPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0`.

Based on my understanding, the only way to fix this 

1) either I upgrade to java 13 (which is not possible in my case )

2) Or Recompile your ProgQuery code for lower version of Java (Java 8). 

So I would appreciate if you could share the binaries/classfiles for Java 8 or tell me how to recompile your code using Java 8 so that I can generate the jar files on my own. Sorry for the confusion, I'm new to Java.
